fail_fast: true
repos:
  - repo: local
    hooks:
      - id: poetry export
        name: export installed packages
        language: system
        entry: poetry export -f requirements.txt -o requirements.txt --without-hashes
        types: [ python ]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
        - id: check-yaml
        - id: end-of-file-fixer
        - id: debug-statements
        - id: check-case-conflict
        - id: check-docstring-first
        - id: check-executables-have-shebangs
        - id: check-merge-conflict
        - id: check-yaml
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-docstring-first

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
        args: [
          "-i", "--ignore-init-module-imports", "--remove-all-unused-imports",
          "--remove-duplicate-keys", "--remove-unused-variables"
        ]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8 except __init__.py
        exclude: /__init__\.py$
        additional_dependencies: ["flake8-bugbear==20.1.4"]
      - id: flake8
        name: flake8 only __init__.py
        args: ["--extend-ignore=F401"] # ignore unused imports in __init__.py
        files: /__init__\.py$
        additional_dependencies: ["flake8-bugbear==20.1.4"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]

  - repo: local
    hooks:
      - id: alembic check
        name: check models
        language: system
        entry: alembic check
        types: [ python ]
        pass_filenames: false

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
      - id: python-safety-dependencies-check
        name: package vulnerability check
        files: pyproject.toml
        args: ["--ignore=70612,73725"]
