version: "3.8"
services:
  web:
    image: email-gateway-service:latest
    container_name: "email-gateway-web"
    restart: on-failure
    env_file:
      - .env
    command: ./start_web.sh
    ports:
      - "5000:8000"
    networks:
      - email_service
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  consumer:
    image: email-gateway-service:latest
    container_name: "email-gateway-consumer"
    restart: on-failure
    env_file:
      - .env
    command: ./start_consumer.sh
    networks:
      - email_service
    depends_on:
      web:
        condition: service_started

  db:
    image: postgres:12
    container_name: "email-gateway-database"
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - $PWD/.ignore_postgres_data:/var/lib/postgresql/data
    ports:
      - "4000:5432"
    networks:
      - email_service
    healthcheck:
        test: ["CMD", "pg_isready",  "-U", "admin", "-d", "admin"]

  redis:
    image: redis:6.2.6-alpine
    container_name: "redis-server"
    restart: on-failure
    command: redis-server --requirepass admin
    ports:
      - "3000:6379"
    networks:
      - email_service
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

networks:
  email_service:
    name: email_network
