"""message type model add column

Revision ID: 6fc322b6d180
Revises: 60f2b3603728
Create Date: 2024-12-13 12:45:05.567006

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6fc322b6d180"
down_revision = "60f2b3603728"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_message_types",
        sa.Column("delivery_mode", sa.String(), server_default="direct", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_message_types", "delivery_mode")
    # ### end Alembic commands ###
